import turtle
wn = turtle.Screen()
wn.bgcolor("green")
mikey = turtle.Turtle()
mikey.shape("turtle")
mikey.pensize(10)
mikey.speed(3)
mikey.color("silver")

mikey.penup()
mikey.goto(-225,0)
mikey.pendown()

mikey.left(60)
mikey.forward(200)
mikey.right(120)
mikey.forward(100)
mikey.right(120)
mikey.forward(100)
mikey.forward(-100)
mikey.left(120)
mikey.forward(100)

mikey.penup()
mikey.right(300)
mikey.forward(20)
mikey.pendown()
mikey.forward(3)
mikey.penup()
mikey.forward(20)
mikey.pendown()

mikey.left(60)
mikey.forward(200)
mikey.right(120)
mikey.forward(100)
mikey.right(120)
mikey.forward(100)
mikey.forward(-100)
mikey.left(120)
mikey.forward(100)

wn.exitonclick()
